name: Update Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Run Python Script
        run: python data_scrapping.py  # Ganti dengan nama file Python Anda
      
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update data $(date +'%Y-%m-%d %H:%M:%S')"
          git push
